// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orientation.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	orientation.proto
	weather.proto

It has these top-level messages:
	OrientationReadings
	OrientationReading
	GyroscopeReading
	MagnetometerReading
	AccelerometerReading
	WeatherReadings
	WeatherReading
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrientationReadings struct {
	Device   string                     `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	BaseTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=base_time,json=baseTime" json:"base_time,omitempty"`
	Readings []*OrientationReading      `protobuf:"bytes,3,rep,name=readings" json:"readings,omitempty"`
}

func (m *OrientationReadings) Reset()                    { *m = OrientationReadings{} }
func (m *OrientationReadings) String() string            { return proto.CompactTextString(m) }
func (*OrientationReadings) ProtoMessage()               {}
func (*OrientationReadings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrientationReadings) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *OrientationReadings) GetBaseTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.BaseTime
	}
	return nil
}

func (m *OrientationReadings) GetReadings() []*OrientationReading {
	if m != nil {
		return m.Readings
	}
	return nil
}

type OrientationReading struct {
	RelativeTimeUs uint32                `protobuf:"varint,1,opt,name=relative_time_us,json=relativeTimeUs" json:"relative_time_us,omitempty"`
	Gyroscope      *GyroscopeReading     `protobuf:"bytes,2,opt,name=gyroscope" json:"gyroscope,omitempty"`
	Magnetometer   *MagnetometerReading  `protobuf:"bytes,3,opt,name=magnetometer" json:"magnetometer,omitempty"`
	Accelerometer  *AccelerometerReading `protobuf:"bytes,4,opt,name=accelerometer" json:"accelerometer,omitempty"`
}

func (m *OrientationReading) Reset()                    { *m = OrientationReading{} }
func (m *OrientationReading) String() string            { return proto.CompactTextString(m) }
func (*OrientationReading) ProtoMessage()               {}
func (*OrientationReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OrientationReading) GetRelativeTimeUs() uint32 {
	if m != nil {
		return m.RelativeTimeUs
	}
	return 0
}

func (m *OrientationReading) GetGyroscope() *GyroscopeReading {
	if m != nil {
		return m.Gyroscope
	}
	return nil
}

func (m *OrientationReading) GetMagnetometer() *MagnetometerReading {
	if m != nil {
		return m.Magnetometer
	}
	return nil
}

func (m *OrientationReading) GetAccelerometer() *AccelerometerReading {
	if m != nil {
		return m.Accelerometer
	}
	return nil
}

// degrees per second
type GyroscopeReading struct {
	XDps float64 `protobuf:"fixed64,1,opt,name=x_dps,json=xDps" json:"x_dps,omitempty"`
	YDps float64 `protobuf:"fixed64,2,opt,name=y_dps,json=yDps" json:"y_dps,omitempty"`
	ZDps float64 `protobuf:"fixed64,3,opt,name=z_dps,json=zDps" json:"z_dps,omitempty"`
}

func (m *GyroscopeReading) Reset()                    { *m = GyroscopeReading{} }
func (m *GyroscopeReading) String() string            { return proto.CompactTextString(m) }
func (*GyroscopeReading) ProtoMessage()               {}
func (*GyroscopeReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GyroscopeReading) GetXDps() float64 {
	if m != nil {
		return m.XDps
	}
	return 0
}

func (m *GyroscopeReading) GetYDps() float64 {
	if m != nil {
		return m.YDps
	}
	return 0
}

func (m *GyroscopeReading) GetZDps() float64 {
	if m != nil {
		return m.ZDps
	}
	return 0
}

// micro teslas
type MagnetometerReading struct {
	XUt float64 `protobuf:"fixed64,1,opt,name=x_ut,json=xUt" json:"x_ut,omitempty"`
	YUt float64 `protobuf:"fixed64,2,opt,name=y_ut,json=yUt" json:"y_ut,omitempty"`
	ZUt float64 `protobuf:"fixed64,3,opt,name=z_ut,json=zUt" json:"z_ut,omitempty"`
}

func (m *MagnetometerReading) Reset()                    { *m = MagnetometerReading{} }
func (m *MagnetometerReading) String() string            { return proto.CompactTextString(m) }
func (*MagnetometerReading) ProtoMessage()               {}
func (*MagnetometerReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MagnetometerReading) GetXUt() float64 {
	if m != nil {
		return m.XUt
	}
	return 0
}

func (m *MagnetometerReading) GetYUt() float64 {
	if m != nil {
		return m.YUt
	}
	return 0
}

func (m *MagnetometerReading) GetZUt() float64 {
	if m != nil {
		return m.ZUt
	}
	return 0
}

// milli earth-gravities
type AccelerometerReading struct {
	XMg float64 `protobuf:"fixed64,1,opt,name=x_mg,json=xMg" json:"x_mg,omitempty"`
	YMg float64 `protobuf:"fixed64,2,opt,name=y_mg,json=yMg" json:"y_mg,omitempty"`
	ZMg float64 `protobuf:"fixed64,3,opt,name=z_mg,json=zMg" json:"z_mg,omitempty"`
}

func (m *AccelerometerReading) Reset()                    { *m = AccelerometerReading{} }
func (m *AccelerometerReading) String() string            { return proto.CompactTextString(m) }
func (*AccelerometerReading) ProtoMessage()               {}
func (*AccelerometerReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AccelerometerReading) GetXMg() float64 {
	if m != nil {
		return m.XMg
	}
	return 0
}

func (m *AccelerometerReading) GetYMg() float64 {
	if m != nil {
		return m.YMg
	}
	return 0
}

func (m *AccelerometerReading) GetZMg() float64 {
	if m != nil {
		return m.ZMg
	}
	return 0
}

func init() {
	proto.RegisterType((*OrientationReadings)(nil), "com.siliconbeacon.iot.messages.OrientationReadings")
	proto.RegisterType((*OrientationReading)(nil), "com.siliconbeacon.iot.messages.OrientationReading")
	proto.RegisterType((*GyroscopeReading)(nil), "com.siliconbeacon.iot.messages.GyroscopeReading")
	proto.RegisterType((*MagnetometerReading)(nil), "com.siliconbeacon.iot.messages.MagnetometerReading")
	proto.RegisterType((*AccelerometerReading)(nil), "com.siliconbeacon.iot.messages.AccelerometerReading")
}

func init() { proto.RegisterFile("orientation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xb1, 0x9d, 0x95, 0x44, 0x5d, 0x47, 0xab, 0x8c, 0x61, 0x72, 0xd8, 0x82, 0x2f, 0xf3,
	0x49, 0x1d, 0xe9, 0x60, 0xe7, 0x95, 0xc2, 0xd8, 0xc1, 0x29, 0xf3, 0x16, 0x06, 0xbd, 0x18, 0xd9,
	0x79, 0x13, 0x02, 0xcb, 0x32, 0x96, 0x52, 0x6c, 0x7f, 0xa4, 0x7d, 0x80, 0x7d, 0x81, 0x7d, 0xb1,
	0x21, 0xcb, 0x4a, 0xdb, 0xb5, 0x34, 0x47, 0xfd, 0xfc, 0xde, 0xef, 0xfd, 0xdf, 0xc3, 0xe8, 0x4c,
	0x36, 0x1c, 0x2a, 0x4d, 0x35, 0x97, 0x15, 0xa9, 0x1b, 0xa9, 0x25, 0x7e, 0x5b, 0x48, 0x41, 0x14,
	0x2f, 0x79, 0x21, 0xab, 0x1c, 0x68, 0x21, 0x2b, 0xc2, 0xa5, 0x26, 0x02, 0x94, 0xa2, 0x0c, 0xd4,
	0xe2, 0x1d, 0x93, 0x92, 0x95, 0x70, 0x3e, 0x54, 0xe7, 0xbb, 0x5f, 0xe7, 0x9a, 0x0b, 0x50, 0x9a,
	0x8a, 0xda, 0x0a, 0xa2, 0x3f, 0x1e, 0x9a, 0x5f, 0xdf, 0x69, 0x53, 0xa0, 0x5b, 0x5e, 0x31, 0x85,
	0xdf, 0xa0, 0xa3, 0x2d, 0xdc, 0xf2, 0x02, 0x42, 0x6f, 0xe9, 0xc5, 0xb3, 0x74, 0x7c, 0xe1, 0x4f,
	0x68, 0x96, 0x53, 0x05, 0x99, 0xf1, 0x84, 0xfe, 0xd2, 0x8b, 0x8f, 0x57, 0x0b, 0x62, 0x87, 0x10,
	0x37, 0x84, 0xfc, 0x70, 0x43, 0xd2, 0xa9, 0x29, 0x36, 0x4f, 0xbc, 0x46, 0xd3, 0x66, 0x94, 0x87,
	0xc1, 0x32, 0x88, 0x8f, 0x57, 0x2b, 0xf2, 0x7c, 0x78, 0xf2, 0x38, 0x57, 0xba, 0x77, 0x44, 0x7f,
	0x7d, 0x84, 0x1f, 0x17, 0xe0, 0x18, 0x9d, 0x36, 0x50, 0x52, 0xcd, 0x6f, 0x6d, 0xc6, 0x6c, 0xa7,
	0x86, 0x0d, 0x4e, 0xd2, 0x57, 0x8e, 0x9b, 0x38, 0x1b, 0x85, 0xd7, 0x68, 0xc6, 0xba, 0x46, 0xaa,
	0x42, 0xd6, 0x6e, 0x93, 0x0f, 0x87, 0x12, 0x7d, 0x71, 0x0d, 0x2e, 0xcf, 0x9d, 0x02, 0xff, 0x44,
	0x2f, 0x05, 0x65, 0x15, 0x68, 0x29, 0x40, 0x43, 0x13, 0x06, 0x83, 0xf2, 0xe2, 0x90, 0x32, 0xb9,
	0xd7, 0xe3, 0xac, 0x0f, 0x44, 0xf8, 0x06, 0x9d, 0xd0, 0xa2, 0x80, 0x12, 0x9a, 0xd1, 0x3c, 0x19,
	0xcc, 0x1f, 0x0f, 0x99, 0x3f, 0xdf, 0x6f, 0x72, 0xea, 0x87, 0xaa, 0xe8, 0x1b, 0x3a, 0xfd, 0x7f,
	0x27, 0x3c, 0x47, 0x2f, 0xda, 0x6c, 0x5b, 0xdb, 0xbb, 0x79, 0xe9, 0xa4, 0xbd, 0xaa, 0x95, 0x81,
	0xdd, 0x00, 0x7d, 0x0b, 0xbb, 0x11, 0xf6, 0x03, 0x0c, 0x2c, 0xec, 0xaf, 0x6a, 0x15, 0xad, 0xd1,
	0xfc, 0x89, 0x9d, 0xf0, 0x19, 0x9a, 0xb4, 0xd9, 0x4e, 0x8f, 0xd2, 0xa0, 0xdd, 0x68, 0x83, 0x3a,
	0x83, 0xac, 0x32, 0xe8, 0x2c, 0xea, 0x0d, 0xb2, 0xc2, 0xa0, 0xdf, 0xe8, 0xe8, 0x1a, 0xbd, 0x7e,
	0x6a, 0x13, 0x2b, 0x14, 0x6c, 0x2f, 0x4c, 0x98, 0x15, 0x0a, 0xb6, 0x17, 0x5a, 0xd4, 0x1b, 0xe4,
	0x84, 0x09, 0xbb, 0x7c, 0x7f, 0x33, 0x75, 0x37, 0xfa, 0xed, 0x2f, 0xbe, 0xdb, 0x03, 0x5e, 0xda,
	0x03, 0x7e, 0x95, 0x9a, 0x24, 0xe3, 0xc7, 0xfc, 0x68, 0xf8, 0xa1, 0x2f, 0xfe, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0x17, 0xc6, 0x0e, 0x78, 0x03, 0x00, 0x00,
}
